# .github/workflows/test.yml

name: Lint and Test

on: [push, pull_request]

env:
  FLASK_FIREBASE_JSON: ${{ secrets.FLASK_FIREBASE_JSON }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run Black 
        run: pipenv run black --check .

      - name: Run Pylint
        run: pipenv run pylint --fail-under=0 *.py **/*.py

      - name: Run Tests
        run: pipenv run pytest