# .github/workflows/test.yml

name: Lint and Test

on: [push, pull_request]

env:
  FLASK_TYPE: ${{ secrets.FLASK_TYPE }}
  FLASK_PROJECT_ID: ${{ secrets.FLASK_PROJECT_ID }}
  FLASK_PRIVATE_KEY_ID: ${{ secrets.FLASK_PRIVATE_KEY_ID }}
  FLASK_PRIVATE_KEY: ${{ secrets.FLASK_PRIVATE_KEY }}
  FLASK_CLIENT_EMAIL: ${{ secrets.FLASK_CLIENT_EMAIL }}
  FLASK_CLIENT_ID: ${{ secrets.FLASK_CLIENT_ID }}
  FLASK_AUTH_URI: ${{ secrets.FLASK_AUTH_URI }}
  FLASK_TOKEN_URI: ${{ secrets.FLASK_TOKEN_URI }}
  FLASK_AUTH_PROVIDER: ${{ secrets.FLASK_AUTH_PROVIDER }}
  FLASK_CLIENT_CERT: ${{ secrets.FLASK_CLIENT_CERT }}

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run Black 
        run: pipenv run black --check .

      - name: Run Pylint
        run: pipenv run pylint *.py **/*.py

      - name: Run Tests
        run: pipenv run pytest